import type { Client, Agent, Service, Inspection, Invoice, ContactLog, ReportTemplate } from '@/types'

export function isDemoMode(): boolean {
  const envDemo = process.env.NEXT_PUBLIC_DEMO_MODE === 'true'
  const hasSupabaseConfig = Boolean(
    process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  )
  return envDemo || !hasSupabaseConfig
}

export const DEMO_USER_ID = 'demo-user-00000000'

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'client-1',
    user_id: DEMO_USER_ID,
    first_name: 'Sarah',
    last_name: 'Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '(555) 234-5678',
    address: '742 Evergreen Terrace, Springfield, IL',
    notes: 'First-time buyer, very detail-oriented. Prefers morning appointments.',
    tags: ['First-Time Buyer', 'VIP'],
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'client-2',
    user_id: DEMO_USER_ID,
    first_name: 'James',
    last_name: 'Thornton',
    email: 'jthornton@gmail.com',
    phone: '(555) 876-3421',
    address: '1600 Oak Lane, Shelbyville, IL',
    notes: 'Investor, owns several rental properties. Needs quick turnaround.',
    tags: ['Investor', 'Past Client'],
    created_at: '2026-01-15T09:00:00Z',
    updated_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'client-3',
    user_id: DEMO_USER_ID,
    first_name: 'Maria',
    last_name: 'Gonzalez',
    email: 'mgonzalez@outlook.com',
    phone: '(555) 512-9087',
    address: null,
    notes: null,
    tags: ['Referral'],
    created_at: '2026-03-01T14:00:00Z',
    updated_at: '2026-03-01T14:00:00Z',
  },
]

export const DEMO_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    user_id: DEMO_USER_ID,
    first_name: 'David',
    last_name: 'Hartwell',
    email: 'david@kwrealty.com',
    phone: '(555) 321-4567',
    brokerage: 'Keller Williams Realty',
    notes: 'Top producer in the Northside market. Sends 3-4 referrals per month.',
    tags: ['Top Referrer', 'VIP Partner'],
    referral_count: 14,
    created_at: '2025-09-01T08:00:00Z',
    updated_at: '2026-02-20T08:00:00Z',
  },
  {
    id: 'agent-2',
    user_id: DEMO_USER_ID,
    first_name: 'Lisa',
    last_name: 'Park',
    email: 'lisa.park@remax.com',
    phone: '(555) 654-9870',
    brokerage: 'RE/MAX Elite',
    notes: 'Specializes in luxury homes. Clients expect premium service.',
    tags: ['Agent Partner'],
    referral_count: 6,
    created_at: '2025-11-01T08:00:00Z',
    updated_at: '2026-01-10T08:00:00Z',
  },
]

export const DEMO_SERVICES: Service[] = [
  {
    id: 'service-1',
    user_id: DEMO_USER_ID,
    name: 'Standard Home Inspection',
    description: 'Full inspection of structure, systems, and components',
    base_price: 37500,
    duration_minutes: 180,
    active: true,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'service-2',
    user_id: DEMO_USER_ID,
    name: 'Radon Testing Add-on',
    description: '48-hour continuous radon test with certified report',
    base_price: 15000,
    duration_minutes: 30,
    active: true,
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'service-3',
    user_id: DEMO_USER_ID,
    name: 'Pre-Listing Inspection',
    description: 'Seller inspection to identify issues before listing',
    base_price: 32500,
    duration_minutes: 150,
    active: true,
    created_at: '2025-09-01T08:00:00Z',
  },
]

export const DEMO_INSPECTIONS: Inspection[] = [
  {
    id: 'inspection-1',
    user_id: DEMO_USER_ID,
    client_id: 'client-1',
    agent_id: 'agent-1',
    service_id: 'service-1',
    address: '412 Maple Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    scheduled_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    scheduled_time: '09:00',
    duration_minutes: 180,
    status: 'scheduled',
    inspection_type: 'General Home Inspection',
    notes: 'Gate code: 1234. Dog on premises — keep gate closed.',
    square_footage: 2100,
    year_built: 1998,
    price: 37500,
    report_locked: true,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    client: DEMO_CLIENTS[0],
    agent: DEMO_AGENTS[0],
  },
  {
    id: 'inspection-2',
    user_id: DEMO_USER_ID,
    client_id: 'client-2',
    agent_id: 'agent-2',
    service_id: 'service-1',
    address: '88 Birchwood Drive',
    city: 'Shelbyville',
    state: 'IL',
    zip: '62565',
    scheduled_date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    scheduled_time: '13:00',
    duration_minutes: 180,
    status: 'scheduled',
    inspection_type: 'Buyer Inspection',
    notes: null,
    square_footage: 3400,
    year_built: 2005,
    price: 37500,
    report_locked: true,
    created_at: '2026-03-02T14:00:00Z',
    updated_at: '2026-03-02T14:00:00Z',
    client: DEMO_CLIENTS[1],
    agent: DEMO_AGENTS[1],
  },
  {
    id: 'inspection-3',
    user_id: DEMO_USER_ID,
    client_id: 'client-2',
    agent_id: 'agent-1',
    service_id: 'service-1',
    address: '220 Riverside Court',
    city: 'Capital City',
    state: 'IL',
    zip: '62702',
    scheduled_date: '2026-02-18',
    scheduled_time: '10:00',
    duration_minutes: 180,
    status: 'completed',
    inspection_type: 'General Home Inspection',
    notes: null,
    square_footage: 1850,
    year_built: 1975,
    price: 37500,
    report_locked: false,
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-02-18T15:00:00Z',
    client: DEMO_CLIENTS[1],
    agent: DEMO_AGENTS[0],
  },
  {
    id: 'inspection-4',
    user_id: DEMO_USER_ID,
    client_id: 'client-3',
    agent_id: 'agent-1',
    service_id: 'service-3',
    address: '7 Prospect Hill Road',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    scheduled_date: '2026-02-05',
    scheduled_time: '09:00',
    duration_minutes: 150,
    status: 'completed',
    inspection_type: 'Pre-Listing Inspection',
    notes: null,
    square_footage: 2600,
    year_built: 2012,
    price: 32500,
    report_locked: false,
    created_at: '2026-01-28T10:00:00Z',
    updated_at: '2026-02-05T13:00:00Z',
    client: DEMO_CLIENTS[2],
    agent: DEMO_AGENTS[0],
  },
]

export const DEMO_INVOICES: Invoice[] = [
  {
    id: 'invoice-1',
    user_id: DEMO_USER_ID,
    inspection_id: 'inspection-1',
    client_id: 'client-1',
    amount: 37500,
    tax_amount: 0,
    total_amount: 37500,
    status: 'pending',
    due_date: null,
    paid_date: null,
    stripe_payment_intent_id: null,
    stripe_payment_link: null,
    pass_card_fee: false,
    notes: null,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    client: DEMO_CLIENTS[0],
    inspection: DEMO_INSPECTIONS[0],
  },
  {
    id: 'invoice-2',
    user_id: DEMO_USER_ID,
    inspection_id: 'inspection-2',
    client_id: 'client-2',
    amount: 37500,
    tax_amount: 0,
    total_amount: 37500,
    status: 'pending',
    due_date: null,
    paid_date: null,
    stripe_payment_intent_id: null,
    stripe_payment_link: null,
    pass_card_fee: false,
    notes: null,
    created_at: '2026-03-02T14:00:00Z',
    updated_at: '2026-03-02T14:00:00Z',
    client: DEMO_CLIENTS[1],
    inspection: DEMO_INSPECTIONS[1],
  },
  {
    id: 'invoice-3',
    user_id: DEMO_USER_ID,
    inspection_id: 'inspection-3',
    client_id: 'client-2',
    amount: 37500,
    tax_amount: 0,
    total_amount: 37500,
    status: 'paid',
    due_date: null,
    paid_date: '2026-02-20',
    stripe_payment_intent_id: 'pi_demo_123',
    stripe_payment_link: null,
    pass_card_fee: false,
    notes: null,
    created_at: '2026-02-18T15:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
    client: DEMO_CLIENTS[1],
    inspection: DEMO_INSPECTIONS[2],
  },
  {
    id: 'invoice-4',
    user_id: DEMO_USER_ID,
    inspection_id: 'inspection-4',
    client_id: 'client-3',
    amount: 32500,
    tax_amount: 0,
    total_amount: 32500,
    status: 'paid',
    due_date: null,
    paid_date: '2026-02-07',
    stripe_payment_intent_id: 'pi_demo_456',
    stripe_payment_link: null,
    pass_card_fee: false,
    notes: null,
    created_at: '2026-02-05T13:00:00Z',
    updated_at: '2026-02-07T09:00:00Z',
    client: DEMO_CLIENTS[2],
    inspection: DEMO_INSPECTIONS[3],
  },
]

export const DEMO_REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: 'template-1',
    user_id: DEMO_USER_ID,
    name: 'Standard Home Inspection Report',
    description: 'Full residential inspection covering all major systems and components.',
    created_at: '2025-09-01T08:00:00Z',
    updated_at: '2026-03-01T08:00:00Z',
    sections: [
      {
        id: 'sec-roof',
        name: 'Roof',
        items: [
          { id: 'r1', name: 'Roof Covering / Shingles', condition: 'fair', recommendation: 'monitor', comment: 'Minor granule loss on south-facing slopes. Estimated 5–7 years of remaining life.', photo_urls: [] },
          { id: 'r2', name: 'Flashings', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'r3', name: 'Gutters & Downspouts', condition: 'fair', recommendation: 'monitor', comment: 'Debris accumulation noted. Recommend cleaning before fall season.', photo_urls: [] },
          { id: 'r4', name: 'Skylights', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'r5', name: 'Chimney', condition: 'poor', recommendation: 'repair', comment: 'Mortar joints are cracked and deteriorating. Crown has visible cracks. Recommend tuckpointing and crown repair before winter.', photo_urls: [] },
          { id: 'r6', name: 'Roof Structure / Decking', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-exterior',
        name: 'Exterior',
        items: [
          { id: 'e1', name: 'Siding / Cladding', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'e2', name: 'Trim & Fascia', condition: 'fair', recommendation: 'monitor', comment: 'Minor paint peeling on north side fascia board.', photo_urls: [] },
          { id: 'e3', name: 'Windows (Exterior)', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'e4', name: 'Exterior Doors', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'e5', name: 'Garage Door & Opener', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'e6', name: 'Driveway & Walkways', condition: 'fair', recommendation: 'monitor', comment: 'Driveway shows minor cracking typical of age.', photo_urls: [] },
          { id: 'e7', name: 'Grading & Drainage', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'e8', name: 'Deck / Patio / Porch', condition: 'poor', recommendation: 'repair', comment: 'Several deck boards are soft and showing signs of rot. Ledger board connection should be evaluated by a licensed contractor.', photo_urls: [] },
        ],
      },
      {
        id: 'sec-foundation',
        name: 'Foundation & Structure',
        items: [
          { id: 'f1', name: 'Foundation Walls', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'f2', name: 'Basement / Crawlspace', condition: 'fair', recommendation: 'monitor', comment: 'Minor efflorescence on lower east wall indicating past moisture intrusion. Currently dry.', photo_urls: [] },
          { id: 'f3', name: 'Structural Framing', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'f4', name: 'Floor Structure', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'f5', name: 'Wall Structure', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-electrical',
        name: 'Electrical',
        items: [
          { id: 'el1', name: 'Main Service Panel', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'el2', name: 'Branch Circuit Wiring', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'el3', name: 'Outlets & Switches', condition: 'fair', recommendation: 'repair', comment: 'Three outlets in the garage are ungrounded (2-prong). Recommend upgrading to grounded outlets.', photo_urls: [] },
          { id: 'el4', name: 'GFCI Protection', condition: 'poor', recommendation: 'safety_hazard', comment: 'GFCI outlets absent at kitchen countertop areas. Required by current code. Recommend immediate installation.', photo_urls: [] },
          { id: 'el5', name: 'AFCI Protection', condition: 'not_inspected', recommendation: 'none', comment: 'Panel does not have AFCI breakers. Not required by original code at time of construction but recommended.', photo_urls: [] },
          { id: 'el6', name: 'Smoke & CO Detectors', condition: 'fair', recommendation: 'repair', comment: 'CO detector absent in utility room adjacent to gas appliances. Recommend adding.', photo_urls: [] },
          { id: 'el7', name: 'Exterior Lighting', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-plumbing',
        name: 'Plumbing',
        items: [
          { id: 'p1', name: 'Water Supply Lines', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'p2', name: 'Drain / Waste / Vent', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'p3', name: 'Water Heater', condition: 'fair', recommendation: 'monitor', comment: 'Water heater is 9 years old (avg. lifespan 10–12 years). TPR valve last tested unknown. Recommend annual servicing.', photo_urls: [] },
          { id: 'p4', name: 'Fixtures & Faucets', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'p5', name: 'Toilets', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'p6', name: 'Sump Pump', condition: 'not_inspected', recommendation: 'none', comment: 'Sump pump not present. Basement does not appear to have active drainage issues.', photo_urls: [] },
          { id: 'p7', name: 'Main Water Shutoff', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-hvac',
        name: 'HVAC',
        items: [
          { id: 'h1', name: 'Heating System / Furnace', condition: 'fair', recommendation: 'repair', comment: 'Furnace is 14 years old. Filter heavily clogged. Recommend professional cleaning and filter replacement.', photo_urls: [] },
          { id: 'h2', name: 'Cooling System / A/C', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'h3', name: 'Ductwork & Distribution', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'h4', name: 'Air Filters', condition: 'poor', recommendation: 'repair', comment: 'Filter is heavily clogged. Replace immediately to prevent HVAC damage.', photo_urls: [] },
          { id: 'h5', name: 'Thermostat', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'h6', name: 'Fireplace / Wood Stove', condition: 'not_inspected', recommendation: 'none', comment: 'Gas fireplace not operational during inspection. Recommend professional evaluation before use.', photo_urls: [] },
        ],
      },
      {
        id: 'sec-attic',
        name: 'Attic',
        items: [
          { id: 'a1', name: 'Attic Access', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'a2', name: 'Insulation', condition: 'fair', recommendation: 'monitor', comment: 'Insulation depth approx. R-19. Current standard is R-49 for this climate zone. Additional insulation recommended.', photo_urls: [] },
          { id: 'a3', name: 'Ventilation', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'a4', name: 'Framing / Rafters', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'a5', name: 'Evidence of Moisture / Staining', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-interior',
        name: 'Interior',
        items: [
          { id: 'i1', name: 'Walls & Ceilings', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'i2', name: 'Floors', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'i3', name: 'Interior Doors', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'i4', name: 'Interior Windows', condition: 'fair', recommendation: 'repair', comment: 'Two bedroom windows show failed seals (fogging between panes). Recommend replacement of affected IGUs.', photo_urls: [] },
          { id: 'i5', name: 'Stairs & Railings', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
      {
        id: 'sec-kitchen',
        name: 'Kitchen',
        items: [
          { id: 'k1', name: 'Cabinets & Drawers', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k2', name: 'Countertops', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k3', name: 'Sink & Faucet', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k4', name: 'Dishwasher', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k5', name: 'Range / Cooktop', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k6', name: 'Oven', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'k7', name: 'Exhaust Fan / Range Hood', condition: 'fair', recommendation: 'monitor', comment: 'Exhaust fan recirculates rather than venting to exterior. Recommend upgrading to ducted exhaust.', photo_urls: [] },
          { id: 'k8', name: 'Refrigerator', condition: 'not_inspected', recommendation: 'none', comment: "Refrigerator is owner's personal property and was not inspected.", photo_urls: [] },
        ],
      },
      {
        id: 'sec-bathrooms',
        name: 'Bathrooms',
        items: [
          { id: 'b1', name: 'Toilet(s)', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'b2', name: 'Sink & Faucet', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'b3', name: 'Shower / Tub', condition: 'fair', recommendation: 'repair', comment: 'Caulk around master bath tub surround is cracked and shows mold growth. Recommend removing and replacing all caulk.', photo_urls: [] },
          { id: 'b4', name: 'Tile, Grout & Caulking', condition: 'fair', recommendation: 'repair', comment: 'Grout missing in several spots in master shower. Reseal or replace to prevent water intrusion.', photo_urls: [] },
          { id: 'b5', name: 'Exhaust Fan', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
          { id: 'b6', name: 'GFCI Outlets', condition: 'good', recommendation: 'none', comment: null, photo_urls: [] },
        ],
      },
    ],
  },
]

export const DEMO_CONTACT_LOGS: ContactLog[] = [
  {
    id: 'log-1',
    user_id: DEMO_USER_ID,
    client_id: 'client-1',
    agent_id: null,
    type: 'email',
    notes: 'Sent booking confirmation email.',
    created_at: '2026-03-01T10:05:00Z',
  },
  {
    id: 'log-2',
    user_id: DEMO_USER_ID,
    client_id: 'client-1',
    agent_id: null,
    type: 'call',
    notes: 'Called to confirm access and gate code. Client confirmed 9am arrival.',
    created_at: '2026-03-04T14:00:00Z',
  },
  {
    id: 'log-3',
    user_id: DEMO_USER_ID,
    client_id: 'client-2',
    agent_id: null,
    type: 'note',
    notes: 'Client interested in radon test add-on for next inspection.',
    created_at: '2026-02-22T11:00:00Z',
  },
]
